# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 02:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usersystem.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=usersystem.models.report_image_upload_path_)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('is_corrected', models.BooleanField(default=False)),
                ('total_grades', models.IntegerField(default=0)),
                ('experiment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report', to='experiment.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='UserBaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='anonymous', max_length=128)),
                ('phone', models.CharField(default='', max_length=64)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=usersystem.models._image_upload_path_)),
                ('group', models.CharField(default='student', max_length=64)),
                ('is_email_active', models.BooleanField(default=False)),
                ('experiment', models.ManyToManyField(related_name='user', to='experiment.Experiment')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userBaseInfo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='usersystem.UserBaseInfo'),
        ),
        migrations.AddField(
            model_name='image',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='usersystem.Report'),
        ),
        migrations.AddField(
            model_name='data',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='usersystem.Report'),
        ),
    ]
