# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='data_processing',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='instrument',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='objective',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='principle',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='process',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='report',
            name='thinking',
            field=models.TextField(default=''),
        ),
    ]
