# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0002_auto_20160816_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='raw_data',
            field=models.TextField(default=''),
        ),
    ]
