# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0004_auto_20160820_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachfile',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
