# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-20 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0005_attachfile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachfile',
            name='name',
            field=models.CharField(default='', max_length=512),
        ),
    ]
