# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0007_websiteconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTag',
            fields=[
                ('tid', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField(default=0)),
                ('reason', models.CharField(default='', max_length=256)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='usersystem.Report')),
            ],
        ),
    ]
