# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0008_reporttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttag',
            name='config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='usersystem.WebsiteConfig'),
        ),
        migrations.AlterField(
            model_name='reporttag',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='usersystem.Report'),
        ),
    ]
