# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0009_auto_20160822_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttag',
            name='html',
            field=models.TextField(default=''),
        ),
    ]
