# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0010_reporttag_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttag',
            name='block',
            field=models.CharField(default='', max_length=128),
        ),
    ]
