# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0011_reporttag_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='show_extra_block',
            field=models.BooleanField(default=True),
        ),
    ]
