# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 05:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0012_websiteconfig_show_extra_block'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('iid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='major', to='usersystem.Institute')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_class', to='usersystem.Major')),
            ],
        ),
        migrations.AddField(
            model_name='userbaseinfo',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='usersystem.StudentClass'),
        ),
    ]
