# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0013_auto_20160822_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbaseinfo',
            name='address',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='userbaseinfo',
            name='is_account_active',
            field=models.BooleanField(default=False),
        ),
    ]
