# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0014_auto_20161008_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_submit',
            field=models.BooleanField(default=False),
        ),
    ]
