# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-29 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0015_report_is_submit'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='back_reason',
            field=models.TextField(default=''),
        ),
    ]
