# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0016_report_back_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='websiteconfig',
            name='welcome_word',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
