# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-20 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0017_websiteconfig_welcome_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='experiment.Experiment'),
        ),
    ]
