# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-25 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0018_auto_20161220_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.IntegerField()),
                ('data', models.TextField(null=True)),
                ('col', models.IntegerField(default=1)),
                ('row', models.IntegerField(default=1)),
                ('name', models.CharField(default='\u672a\u547d\u540d', max_length=128)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_table', to='usersystem.Report')),
            ],
        ),
    ]
