# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-27 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usersystem', '0019_datatable'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='corrected_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
